language: java

install:
  - "./gradlew assemble"

script:
  - "./gradlew verify"
  
jdk:
  - oraclejdk8
  
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6

notifications:
  email: false
