// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5933.LikeARecord;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import jaci.openrio.toast.lib.registry.Registrar;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainCANTalon1;
    public static CANTalon driveTrainCANTalon2;
    public static CANTalon driveTrainCANTalon3;
    public static SpeedController driveTrainSpeedController1;
    public static RobotDrive driveTrainRobotDrive;
    public static PowerDistributionPanel powerPowerDistributionPanel;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainCANTalon1 = Registrar.canTalon(10);
        LiveWindow.addActuator("Drive Train", "CAN Talon 1", driveTrainCANTalon1);
        
        driveTrainCANTalon2 = Registrar.canTalon(11);
        LiveWindow.addActuator("Drive Train", "CAN Talon 2", driveTrainCANTalon2);
        
        driveTrainCANTalon3 = Registrar.canTalon(12);
        LiveWindow.addActuator("Drive Train", "CAN Talon 3", driveTrainCANTalon3);
        
        driveTrainSpeedController1 = Registrar.victorSP(0);
        LiveWindow.addActuator("Drive Train", "Speed Controller 1", (Talon) driveTrainSpeedController1);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainCANTalon1, driveTrainCANTalon2,
              driveTrainCANTalon3, driveTrainSpeedController1);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);

        powerPowerDistributionPanel = new PowerDistributionPanel(2);
        LiveWindow.addSensor("Power", "PowerDistributionPanel", powerPowerDistributionPanel);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
